let LOCALIZATION = {
    text: {
        EN: 'Media planning is constructive.' +
        ' The main stage of the market research, at first glance, generated by time.' +
        'Production distorts the complex social status.',
        RU: 'Медиапланирование конструктивно.' +
        'Основная стадия проведения рыночного исследования, на первый взгляд, порождена временем.' +
        'Производство искажает комплексный социальный статус.'
    },
    branding: {
        EN: '#branding',
        RU: '#брендинг'
    },
    view: {
        EN: 'VIEW',
        RU: 'СМОТРЕТЬ'
    },
    company: {
        EN: 'COMPANY',
        RU: 'КОМПАНИЯ'
    },
    clients: {
        EN: 'CLIENTS',
        RU: 'КЛИЕНТЫ'
    },
    services: {
        EN: 'SERVICES',
        RU: 'УСЛУГИ'
    },
    career: {
        EN: 'CAREER',
        RU: 'КАРЬЕРА'
    },
    awards: {
        EN: 'AWARDS',
        RU: 'НАГРАДЫ'
    }
};